version: "3.0"

services:
    sitio1:
        image:          nginx
        container_name: sitio1
        ports:
                      - 8081:80
        volumes:
                        # Sobreescribo el archivo de configuración que viene por defecto dentro de la imagen del contenedor de nginx
                        # Pongo mi propio archivo de configuración
                      - /home/ubuntu/environment/curso/configuraciones/sitio1/nginx.conf:/etc/nginx/nginx.conf
                        # Que mi nginx tenga acceso a mi sitio WEB
                      - /home/ubuntu/environment/curso/sitiosweb/sitio1:/sitios/sitio1
